import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/uicontrols">UIControls</Link>
        </li>
        <li>
          <Link to="/cards">Cards</Link>
        </li>
        <li>
          <Link to="/charactersfive">CharactersFive</Link>
        </li>
        <li>
          <Link to="/charactersone">CharactersOne</Link>
        </li>
        <li>
          <Link to="/characterstwo">CharactersTwo</Link>
        </li>
        <li>
          <Link to="/characters">Characters</Link>
        </li>
        <li>
          <Link to="/charactersfour">CharactersFour</Link>
        </li>
        <li>
          <Link to="/charactersthree">CharactersThree</Link>
        </li>
        <li>
          <Link to="/styleguide">StyleGuide</Link>
        </li>
        <li>
          <Link to="/cover">Cover</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
